CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(500) NOT NULL,
    mobile_number VARCHAR(20) UNIQUE,
    account_holder VARCHAR(30) NOT NULL,
    tax_code VARCHAR(16) NOT NULL,
    country VARCHAR(30) NOT NULL,
    province VARCHAR(50) NOT NULL,
    town VARCHAR(50) NOT NULL,
    address VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP DEFAULT NULL,
    updated_by VARCHAR(255) DEFAULT NULL
);