server.port=8081

spring.datasource.url=jdbc:mysql://${DATABASE_HOST:user-db}:${DATABASE_PORT:3306}/zeta_user?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update