server.port=8083

spring.datasource.url=jdbc:mysql://${DATABASE_HOST:userdetails-db}:${DATABASE_PORT:3306}/zeta_userdetails?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect