server.port=8082

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:storage-db}:${DATABASE_PORT:5432}/zeta_storage
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect